### PR TITLE
Alex/send recv multipart messages

### LINKED ISSUE #119: Allow all socket types to send multipart messages
As far as I can see from the current code REQ/REP and PUB/SUB sockets can't send multipart messages.  That seems to be inconsistent with the spec.  I have made some changes [here](https://github.com/nhuff/zmq.rs/tree/multipart) to support sending multipart messages on all sockets.  The change is fairly intrusive since it changes the ZmqMessage struct to be a wrapper around a VecDeque<Bytes> instead of just a Bytes field.  It also changes all the send/recv methods to take and return ZmqMessage structs.  I figured it might be worth discussion before I opened a really big pull request.

### PR DESCRIPTION
**Pull request by Alexei-Kornienko**
Closes #119

### CODE REVIEW

**Comment by Alexei-Kornienko** [comment]
In subsequent commits we may remove ZmqMessage completely cause now it's only a thin wrapper over bytes and we might not need it at all

**Comment by TheButlah** [comment]
It looks like this exposes Message::Command and the other internal variants. I don't think we should expose this to the end user as it's an internal representation

**Comment by TheButlah** [comment]
What are your thoughts on using a trait for conversion in the public api?

**Comment by Alexei-Kornienko** [comment]
@TheButlah I thought that this might be useful for some future complex scenario when some use would also be able to send commands to somehow manipulate socket options for example. Do we have an RFC in zeromq somewhere that actually explains how commands work? Cause I was not able to find it quickly.

**Comment by TheButlah** [comment]
i thought commands were simply part of the ZMTP protocol but not actually part of the user level API?

**Comment by Alexei-Kornienko** [comment]
>What are your thoughts on using a trait for conversion in the public api?

you mean something like `IntoZmqMessage`? IMHO it makes API a little less obvious cause you need to refer docs to check what types actually support this conversion. I'm not sure how often such approach is used in other crates. Is there some kind of a best practice guide for this?

>i thought commands were simply part of the ZMTP protocol but not actually part of the user level API?

That's the problem I don't actually know what commands are supposed to do. Client socket needs to be able to set up and identity for itself but from what I know it's done during handshake and should be done via socket options. But there may be other stuff that is sent via commands

**Comment by Alexei-Kornienko** [comment]
Looked over all RFCs again. It seems that commands are only mentioned as part of different security mechanisms so there should be visible to user. In such case I agree that exposing Message enum as a parameter is a good option.

**Comment by Alexei-Kornienko** [comment]
>What are your thoughts on using a trait for conversion in the public api?

@TheButlah another thing to take into account is that we have a ReturnToSender error. We should not drop user messages that we cannot send and we should return them via this error. If we use trait as a parameter what type should we actually return? cause it might not be a good idea to return plain Bytes to user (especially if we prepended them with some envelope)

**Comment by TheButlah** [comment]
>Is there some kind of a best practice guide for this?

We don't want to go crazy with traits as arguments because it adds a small amount of mental complexity, but used tastefully it should be fine. In fact, you're already using it prolificly in tokio via the [bind](https://docs.rs/tokio/1.0.1/tokio/net/struct.TcpListener.html#method.bind) function. Here's some additional common examples from popular crates that use this approach:
- https://docs.rs/reqwest/0.11.0/reqwest/fn.get.html
- https://docs.rs/zmq/0.9.2/zmq/struct.Socket.html#method.send and https://docs.rs/zmq/0.9.2/zmq/struct.Socket.html#method.send_multipart
- Anything that uses IntoIterator
- Plenty examples in std lib: 
- Many more, didn't want to list them all.

**Comment by TheButlah** [comment]
>If we use trait as a parameter what type should we actually return? cause it might not be a good idea to return plain Bytes to user (especially if we prepended them with some envelope)

This is the most perplexing problem. We know that internally we have the `Message` enum, which we shouldn't expose to the user. So since we need to return their sent message(s) in the event of an error, there has to be some way of returning that.

I know there are a lot of draft PRs floating around, but I'm going to submit one and let me know what you think.

**Comment by Alexei-Kornienko** [comment]
Obsolete. #122 merged instead of this

**Pull request closed without merging**
