### PR TITLE
Add some doc comments

### PR DESCRIPTION
**Pull request by mental32**
Hello! I'm interested in helping out in growing and maintaining this crate.

As a first diff I've added doc-comments on all the public items.

### CODE REVIEW

**Comment by Alexei-Kornienko** [comment]
Hi @mental32 . Sorry for the long response time. I would gladly accept any help. Could you please rebase your request according to recent changes to master? It's also possible to split it into smaller requests to merge them faster.

**Comment by mental32** [comment]
@Alexei-Kornienko No worries :)

I was just looking over the changes and I thought to ask if documenting the private items would be useful? (there's a [clippy lint about this](https://rust-lang.github.io/rust-clippy/master/index.html#missing_docs_in_private_items)).

**Comment by Alexei-Kornienko** [comment]
@mental32 IMHO it would be usefull. We'll also need to add actual checks on CI to ensure that we'll keep the same rules for future changes

**Comment by mental32** [comment]
👍 Understood, I'll get the rebase + changes in soon-ish

**Comment by Alexei-Kornienko** [comment]
Obsolete. Pls reopen if needed

**Pull request closed without merging**
